# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from utils.openFileWidget import App
import os


class Ui_MainWindows(object):
    html_output = """<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">
                                             <html><head></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8pt; font-weight:400; font-style:normal;\">"""

    def __init__(self, exe_time, data, selectedprogram):
        self.exe_time = exe_time
        self.selectedprogram = selectedprogram
        self.data = data
        self.html_output = self.html_output + \
            "<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">" + \
            str(data) + "</p></body></html>"

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.algoName = QtWidgets.QLabel(self.centralwidget)
        self.algoName.setObjectName("algoName")
        self.gridLayout.addWidget(self.algoName, 0, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(
            426, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 0, 1, 1, 1)
        self.timeOfExecution = QtWidgets.QLabel(self.centralwidget)
        self.timeOfExecution.setObjectName("timeOfExecution")
        self.gridLayout.addWidget(self.timeOfExecution, 0, 2, 1, 1)
        self.time = QtWidgets.QLabel(self.centralwidget)
        self.time.setObjectName("time")
        self.gridLayout.addWidget(self.time, 0, 3, 1, 1)
        self.output = QtWidgets.QTextEdit(self.centralwidget)
        self.output.setObjectName("output")
        self.gridLayout.addWidget(self.output, 1, 0, 1, 3)

        self.save = QtWidgets.QPushButton(self.centralwidget)
        self.save.setObjectName("save")
        self.save.clicked.connect(
            self.save_button)  # save button  action

        self.gridLayout.addWidget(self.save, 2, 3, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def save_button(self):
        try:
            ex = App()
            ex.saveFileDialog()
            f = open(ex.filename, "a")
            f.write(str(self.data))
            f.close()
        except:
            try:
                os.remove(ex.filename)
                print("An exception occurred")
            except:
                print("An exception occurred 2")

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.algoName.setText(_translate(
            "MainWindow", str(self.selectedprogram)))
        self.timeOfExecution.setText(_translate(
            "MainWindow", "Time For Execution"))
        self.time.setText(_translate(
            "MainWindow", str(round(self.exe_time, 4))))
        self.output.setHtml(self.html_output)
        self.save.setText(_translate("MainWindow", "Save"))
